# Generated by cpp11: do not edit by hand

cpp_connect <- function(driver_id) {
  .Call(`_adbc_cpp_connect`, driver_id)
}

cpp_disconnect <- function(connection_id) {
  invisible(.Call(`_adbc_cpp_disconnect`, connection_id))
}

cpp_load_driver <- function(connection, entrypoint) {
  .Call(`_adbc_cpp_load_driver`, connection, entrypoint)
}
