# Generated by cpp11: do not edit by hand

cpp_connect <- function(driver_id) {
  .Call(`_adbc_cpp_connect`, driver_id)
}

cpp_disconnect <- function(connection_id) {
  invisible(.Call(`_adbc_cpp_disconnect`, connection_id))
}

cpp_load_driver <- function(connection, entrypoint) {
  .Call(`_adbc_cpp_load_driver`, connection, entrypoint)
}

cpp_use_radbc_driver <- function(driver_) {
  .Call(`_adbc_cpp_use_radbc_driver`, driver_)
}

cpp_send_query <- function(connection_id, sql) {
  .Call(`_adbc_cpp_send_query`, connection_id, sql)
}

cpp_send_statement <- function(connection_id, sql) {
  .Call(`_adbc_cpp_send_statement`, connection_id, sql)
}

cpp_clear_result <- function(connection_id) {
  invisible(.Call(`_adbc_cpp_clear_result`, connection_id))
}
